#!/usr/bin/env python3
"""Generate scanner-facing Vala binding artifacts from binding metadata."""

from __future__ import annotations

from pathlib import Path
import re
import tomllib

ROOT = Path(__file__).resolve().parents[1]
METADATA = ROOT / "metadata" / "api.toml"

FUNCTION_RE = re.compile(r"^[\w\s\*]+\b(mln_vala_\w+)\s*\(", re.MULTILINE)
TYPE_PATTERNS = [
    re.compile(r"typedef struct _(MlnVala\w+)\s+\1;"),
    re.compile(r"}\s+(MlnVala\w+);"),
    re.compile(r"typedef\s+\w+\s*\(\*(MlnVala\w+)\)"),
]


def metadata_path(value: str) -> Path:
    path = Path(value)
    if path.is_absolute():
        return path
    return (ROOT / path).resolve()


def load_metadata() -> dict:
    with METADATA.open("rb") as metadata_file:
        return tomllib.load(metadata_file)


def extract_functions(header: str) -> list[str]:
    return sorted(set(FUNCTION_RE.findall(header)))


def extract_types(header: str) -> list[str]:
    types: set[str] = set()
    for pattern in TYPE_PATTERNS:
        types.update(pattern.findall(header))
    return sorted(types)


def check_inventory(kind: str, expected: list[str], actual: list[str]) -> None:
    expected_set = set(expected)
    actual_set = set(actual)
    missing = sorted(expected_set - actual_set)
    undocumented = sorted(actual_set - expected_set)
    if missing or undocumented:
        lines = [f"{kind} inventory mismatch"]
        if missing:
            lines.append("missing from scanner header source:")
            lines.extend(f"  - {name}" for name in missing)
        if undocumented:
            lines.append(
                "present in scanner header source but absent from metadata/api.toml:"
            )
            lines.extend(f"  - {name}" for name in undocumented)
        raise SystemExit("\n".join(lines))


def render_header(metadata: dict, source_header: str) -> str:
    namespace = metadata["namespace"]
    inventory = metadata["public_inventory"]
    source = metadata["scanner_header"]["source"]
    return (
        "/*\n"
        " * This scanner-facing header is generated by bindings/vala/tools/generate.py.\n"
        " * Inputs: bindings/vala/metadata/api.toml and "
        f"bindings/vala/{source}.\n"
        " * Edit metadata or the Rust adapter header source; do not edit build/include output.\n"
        f" * GIR namespace: {namespace['gir_namespace']}-{namespace['gir_version']}; "
        f"Vala namespace: {namespace['vala_namespace']}.\n"
        f" * Metadata inventory: {len(inventory['functions'])} functions, "
        f"{len(inventory['types'])} public C types.\n"
        " */\n\n" + source_header
    )


def main() -> None:
    metadata = load_metadata()
    scanner_header = metadata["scanner_header"]
    source_path = metadata_path(scanner_header["source"])
    output_path = metadata_path(scanner_header["output"])
    source_header = source_path.read_text()

    inventory = metadata["public_inventory"]
    check_inventory(
        "function", inventory["functions"], extract_functions(source_header)
    )
    check_inventory("type", inventory["types"], extract_types(source_header))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_header(metadata, source_header))


if __name__ == "__main__":
    main()
