[env]
ANDROID_HOME = { required = true }

[tasks.build]
run = "../../gradlew :bindings:java-jni:assembleDebug"

[tasks.test]
depends = ["build"]
run = "../../gradlew :bindings:java-jni:connectedDebugAndroidTest"
